image: cr.agilicus.com/corp-tools/docker-compose

variables:
  DOCKER_DRIVER: overlay2
  PORT: 2375
  DOCKER_HOST: tcp://localhost:2375
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH
  TAIGA_CONTAINER_REGISTRY: $CI_REGISTRY/$CI_PROJECT_PATH/

stages:
  - build
  - scan
  - test

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

services:
  - name: docker:dind

build:
  stage: build
  script:
    - echo Start build
    - touch environment
    - echo Build with TAIGA_CONTAINER_REGISTRY=$TAIGA_CONTAINER_REGISTRY
    - docker-compose build
    - docker tag $CI_REGISTRY/$CI_PROJECT_PATH/taiga_backend:latest $CI_REGISTRY/$CI_PROJECT_PATH/taiga_backend:$CI_BUILD_REF_NAME
    - docker tag $CI_REGISTRY/$CI_PROJECT_PATH/taiga_events:latest $CI_REGISTRY/$CI_PROJECT_PATH/taiga_events:$CI_BUILD_REF_NAME
    - docker tag $CI_REGISTRY/$CI_PROJECT_PATH/taiga_frontend:latest $CI_REGISTRY/$CI_PROJECT_PATH/taiga_frontend:$CI_BUILD_REF_NAME
    - docker tag $CI_REGISTRY/$CI_PROJECT_PATH/taiga_celeryworker:latest $CI_REGISTRY/$CI_PROJECT_PATH/taiga_celeryworker:$CI_BUILD_REF_NAME
    - docker images
    - docker-compose push
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/taiga_backend:$CI_BUILD_REF_NAME
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/taiga_events:$CI_BUILD_REF_NAME
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/taiga_frontend:$CI_BUILD_REF_NAME
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/taiga_celeryworker:$CI_BUILD_REF_NAME

scan:
  stage: scan
  artifacts:
    name: "$CI_PROJECT_PATH-$CI_COMMIT_REF_NAME"
    paths:
      - reports/
  script:
    - echo Analyse $CI_REGISTRY/$CI_PROJECT_PATH/taiga_backend:$CI_BUILD_REF_NAME for vulnerability
    - clairctl analyze --log-level debug $CI_REGISTRY/$CI_PROJECT_PATH/taiga_backend:$CI_BUILD_REF_NAME || true
    - echo Analyse $CI_REGISTRY/$CI_PROJECT_PATH/taiga_frontend:$CI_BUILD_REF_NAME for vulnerability
    - clairctl analyze --log-level debug $CI_REGISTRY/$CI_PROJECT_PATH/taiga_frontend:$CI_BUILD_REF_NAME || true
    - echo Analyse $CI_REGISTRY/$CI_PROJECT_PATH/taiga_events:$CI_BUILD_REF_NAME for vulnerability
    - clairctl analyze --log-level debug $CI_REGISTRY/$CI_PROJECT_PATH/taiga_events:$CI_BUILD_REF_NAME || true
    - echo Analyse $CI_REGISTRY/$CI_PROJECT_PATH/taiga_celeryworker:$CI_BUILD_REF_NAME for vulnerability
    - clairctl analyze --log-level debug $CI_REGISTRY/$CI_PROJECT_PATH/taiga_celeryworker:$CI_BUILD_REF_NAME || true
    - echo Generate JSON report
    - clairctl report -f json $CI_REGISTRY/$CI_PROJECT_PATH/taiga_backend:$CI_BUILD_REF_NAME || true
    - clairctl report -f json $CI_REGISTRY/$CI_PROJECT_PATH/taiga_frontend:$CI_BUILD_REF_NAME || true
    - clairctl report -f json $CI_REGISTRY/$CI_PROJECT_PATH/taiga_events:$CI_BUILD_REF_NAME || true
    - clairctl report -f json $CI_REGISTRY/$CI_PROJECT_PATH/taiga_celeryworker:$CI_BUILD_REF_NAME || true
    - echo Generate HTML report
    - clairctl report -f html $CI_REGISTRY/$CI_PROJECT_PATH/taiga_backend:$CI_BUILD_REF_NAME || true
    - clairctl report -f html $CI_REGISTRY/$CI_PROJECT_PATH/taiga_frontend:$CI_BUILD_REF_NAME || true
    - clairctl report -f html $CI_REGISTRY/$CI_PROJECT_PATH/taiga_events:$CI_BUILD_REF_NAME || true
    - clairctl report -f html $CI_REGISTRY/$CI_PROJECT_PATH/taiga_celeryworker:$CI_BUILD_REF_NAME || true

test:
  stage: test
  script:
    - echo Start unit-test
