image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  PORT: 2375
  DOCKER_HOST: tcp://localhost:2375
  TAIGA_CONTAINER_REGISTRY=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/

services:
- name: docker:dind

build:
  stage: build
  script:
  - echo Start build
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - docker-compose build
  - docker-compose push
#  - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/taiga_backend
#  - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/taiga_frontend
#  - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/taiga_celeryworker
#  - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/taiga_events
