image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  PORT: 2375
  DOCKER_HOST: tcp://localhost:2375
  TAIGA_CONTAINER_REGISTRY: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/

services:
- name: docker:dind

# We cannot do this, since the image is MUSL-based
#  - wget -O /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
#  - echo "8a11713e11ed73abcb3feb88cd8b5674b3320ba33b22b2ba37915b4ecffdf042  docker-compose" > /usr/local/bin/docker-compose.sha256sum
#  - (cd /usr/local/bin; sha256sum -c docker-compose.sha256sum)
#  - chmod 555 /usr/local/bin/docker-compose
build:
  stage: build
  script:
  - echo Start build
  - apk update
  - apk add py-pip
  - pip install docker-compose
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - touch environment
  - docker-compose build
  - docker-compose push
#  - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/taiga_backend
#  - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/taiga_frontend
#  - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/taiga_celeryworker
#  - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/taiga_events
